
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security_login:
    path: login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        methods: POST

fos_user_security_logout:
    path: logout
    defaults: { _controller: FOSUserBundle:Security:logout }